// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jayreyhmnjaymutadues.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpheXJleWhtbmpheW11dGFkdWVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2OTYwNTAsImV4cCI6MjA2NzI3MjA1MH0.RgU5NNqOoUmJi8URIXzEDTxWui87U8-eDhTWp9QCf10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});